name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # runs once a day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
       contents: write



    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@master
        with:
          github_user_name: Ashvitha22
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push Snake File
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/github-contribution-grid-snake.svg || echo "Skip"
          git commit -m "Update snake" || echo "Skip"
          git push || echo "Skip"
