name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"     # runs daily at 00:00 UTC
  workflow_dispatch:         # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # allow pushing to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Ashvitha22
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and push snake
        run: |
          ls -R
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg || echo "Nothing to add"
          git commit -m "Add/Update snake animation" || echo "Nothing to commit"
          git push || echo "Nothing to push"
